AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM GitSync Stack to create groups and users"

Resources:
  # Secret for the one-time password
  OneTimePasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "one-time-password"
      GenerateSecretString:
        PasswordLength: 12
        ExcludeCharacters: '"@/\'
  
  # S3 Group
  S3Group:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "S3ReadOnlyGroup"
  
  S3GroupPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "S3ReadOnlyPolicy"
      Groups:
        - !Ref S3Group
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "s3:ListAllMyBuckets"
            Resource: "*"
  
  # EC2 Group
  EC2Group:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "EC2ReadOnlyGroup"
  
  EC2GroupPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "EC2ReadOnlyPolicy"
      Groups:
        - !Ref EC2Group
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "ec2:Describe*"
            Resource: "*"
  
  # s3-user
  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: "s3-user"
      Groups: [!Ref S3Group]
      LoginProfile:
        Password: !Sub "{{resolve:secretsmanager:${OneTimePasswordSecret}::SecretString}}"
        PasswordResetRequired: true
  
  # ec2-user
  EC2User:
    Type: AWS::IAM::User
    Properties:
      UserName: "ec2-user"
      Groups: [!Ref EC2Group]
      LoginProfile:
        Password: !Sub "{{resolve:secretsmanager:${OneTimePasswordSecret}::SecretString}}"
        PasswordResetRequired: true
template-file-path: iam-roger.yml
parameters: {}
tags: {}