AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template that creates two IAM user groups (S3 Read-Only v2 and EC2 Read-Only v2),
  a temporary password in AWS Secrets Manager, and two IAM users with console access assigned to these groups.

Resources:
  NewUserTempPasswordV2:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Temporary password for new IAM users (v2)"
      Name: "iam-user-temp-password-v2"
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: "password"
        PasswordLength: 20
        IncludeSpace: false
        RequireEachIncludedType: true

  S3UserGroupV2:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "S3-ReadOnly-Group-V2"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"

  EC2UserGroupV2:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "EC2-ReadOnly-Group-V2"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"

  S3UserV2:
    Type: AWS::IAM::User
    Properties:
      UserName: "roger_s3_v2"
      LoginProfile:
        Password: !Sub "{{resolve:secretsmanager:iam-user-temp-password-v2:SecretString:password}}"
        PasswordResetRequired: true

  EC2UserV2:
    Type: AWS::IAM::User
    Properties:
      UserName: "roger_ec2_v2"
      LoginProfile:
        Password: !Sub "{{resolve:secretsmanager:iam-user-temp-password-v2:SecretString:password}}"
        PasswordResetRequired: true

  S3UserToGroupAdditionV2:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref S3UserGroupV2
      Users:
        - !Ref S3UserV2

  EC2UserToGroupAdditionV2:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref EC2UserGroupV2
      Users:
        - !Ref EC2UserV2

Outputs:
  IAMLoginURLV2:
    Description: "The URL for IAM users (v2) to log in to the AWS Console."
    Value: !Sub "https://console.aws.amazon.com/console/home?region=${AWS::Region}"
  SecretARNV2:
    Description: "The ARN of the secret (v2) containing the temporary password."
    Value: !Ref NewUserTempPasswordV2
