AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template that creates two IAM user groups,
  a temporary password in AWS Secrets Manager, and two IAM users with console access assigned to these groups.

Resources:
  NewUserTempPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Temporary password for new IAM users"
      Name: "temporary-password-iam"
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: "password"
        PasswordLength: 20
        IncludeSpace: false
        RequireEachIncludedType: true

  S3UserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "S3-ReadOnly-Group"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
        - "arn:aws:iam::aws:policy/IAMUserChangePassword"

  EC2UserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "EC2-ReadOnly-Group"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"
        - "arn:aws:iam::aws:policy/IAMUserChangePassword"

  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: "roger_s3"
      LoginProfile:
        Password: "{{resolve:secretsmanager:temporary-password-iam:SecretString:password}}"
        PasswordResetRequired: true

  EC2User:
    Type: AWS::IAM::User
    Properties:
      UserName: "roger_ec2"
      LoginProfile:
        Password: "{{resolve:secretsmanager:temporary-password-iam:SecretString:password}}"
        PasswordResetRequired: true

  EC2UserTest:
    Type: AWS::IAM::User
    Properties:
      UserName: "roger_ec2_test"
      LoginProfile:
        Password: "{{resolve:secretsmanager:temporary-password-iam:SecretString:password}}"
        PasswordResetRequired: true

  S3UserToGroupAddition:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref S3UserGroup
      Users:
        - !Ref S3User

  EC2UserToGroupAddition:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref EC2UserGroup
      Users:
        - !Ref EC2User

Outputs:
  IAMLoginURL:
    Description: "The URL for IAM users to log in to the AWS Console."
    Value: !Sub "https://${AWS::AccountId}.signin.aws.amazon.com/console"

  SecretARN:
    Description: "The ARN of the secret containing the temporary password."
    Value: !Ref NewUserTempPassword
